<?
$arTooltips = array(
	"IBLOCK_TYPE" => GetMessage("IBLOCK_TYPE_TIP"),
	"IBLOCK_ID" => GetMessage("IBLOCK_ID_TIP"),
	"SECTION_ID" => GetMessage("SECTION_ID_TIP"),
	"ELEMENT_ID" => GetMessage("ELEMENT_ID_TIP"),
	"SECTION_CODE" => GetMessage("SECTION_CODE_TIP"),
	"ELEMENT_CODE" => GetMessage("ELEMENT_CODE_TIP"),
	"SECTION_URL" => GetMessage("SECTION_URL_TIP"),
	"DETAIL_URL" => GetMessage("DETAIL_URL_TIP"),
	"DETAIL_EDIT_URL" => GetMessage("DETAIL_EDIT_URL_TIP"),
	"UPLOAD_URL" => GetMessage("UPLOAD_URL_TIP"),
	"DISPLAY_PANEL" => GetMessage("DISPLAY_PANEL_TIP"),
	"SET_TITLE" => GetMessage("SET_TITLE_TIP"),
	"CACHE_TYPE" => GetMessage("CACHE_TYPE_TIP"),
	"CACHE_TIME" => GetMessage("CACHE_TIME_TIP"),
	"ELEMENT_SORT_FIELD" => GetMessage("ELEMENT_SORT_FIELD_TIP"),
	"ELEMENT_SORT_ORDER" => GetMessage("ELEMENT_SORT_ORDER_TIP"),
	"DATE_TIME_FORMAT" => GetMessage("DATE_TIME_FORMAT_TIP"),
);
?>