<?
$arTooltips = array(
	"SET_TITLE" => GetMessage("SET_TITLE_TIP"),
	"USER_PROPERTY" => GetMessage("USER_PROPERTY_TIP"),
	"USER_PROPERTY_NAME" => GetMessage("USER_PROPERTY_NAME_TIP"),
	"AJAX_MODE" => GetMessage("AJAX_MODE_TIP"),
	"AJAX_OPTION_SHADOW" => GetMessage("AJAX_OPTION_SHADOW_TIP"),
	"AJAX_OPTION_JUMP" => GetMessage("AJAX_OPTION_JUMP_TIP"),
	"AJAX_OPTION_STYLE" => GetMessage("AJAX_OPTION_STYLE_TIP"),
	"AJAX_OPTION_HISTORY" => GetMessage("AJAX_OPTION_HISTORY_TIP"),
);
?>