<?
$arTooltips = array(
	"IBLOCK_TYPE" => GetMessage("IBLOCK_TYPE_TIP"),
	"IBLOCK_ID" => GetMessage("IBLOCK_ID_TIP"),
	"SECTION_ID" => GetMessage("SECTION_ID_TIP"),
	"SECTION_CODE" => GetMessage("SECTION_CODE_TIP"),
	"PAGE_ELEMENTS" => GetMessage("PAGE_ELEMENTS_TIP"),
	"SORT_BY" => GetMessage("SORT_BY_TIP"),
	"SORT_ORD" => GetMessage("SORT_ORD_TIP"),
	"ALBUM_PHOTO_SIZE" => GetMessage("ALBUM_PHOTO_SIZE_TIP"),
	"ALBUM_PHOTO_THUMBS_SIZE" => GetMessage("ALBUM_PHOTO_THUMBS_SIZE_TIP"),
	"INDEX_URL" => GetMessage("INDEX_URL_TIP"),
	"SECTION_URL" => GetMessage("SECTION_URL_TIP"),
	"SECTION_EDIT_URL" => GetMessage("SECTION_EDIT_URL_TIP"),
	"SECTION_EDIT_ICON_URL" => GetMessage("SECTION_EDIT_ICON_URL_TIP"),
	"UPLOAD_URL" => GetMessage("UPLOAD_URL_TIP"),
	"PAGE_NAVIGATION_TEMPLATE" => GetMessage("PAGE_NAVIGATION_TEMPLATE_TIP"),
	"DISPLAY_PANEL" => GetMessage("DISPLAY_PANEL_TIP"),
	"DATE_TIME_FORMAT" => GetMessage("DATE_TIME_FORMAT_TIP"),
	"CACHE_TYPE" => GetMessage("CACHE_TYPE_TIP"),
	"CACHE_TIME" => GetMessage("CACHE_TIME_TIP"),
);
?>