insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (68, 'S', ':D :-D', 'icon_biggrin.gif', 'FICON_BIGGRIN', 'N', 30, 16, 16) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (69, 'S', ':) :-)', 'icon_smile.gif', 'FICON_SMILE', 'N', 10, 16, 16) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (70, 'S', ':( :-(', 'icon_sad.gif', 'FICON_SAD', 'N', 50, 16, 16) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (71, 'S', ':o :-o :shock:', 'icon_eek.gif', 'FICON_EEK', 'N', 90, 16, 16) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (72, 'S', '8) 8-)', 'icon_cool.gif', 'FICON_COOL', 'N', 40, 16, 16) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (73, 'S', ':{} :-{}', 'icon_kiss.gif', 'FICON_KISS', 'N', 110, 16, 16) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (74, 'S', ':oops:', 'icon_redface.gif', 'FICON_REDFACE', 'Y', 100, 16, 16) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (75, 'S', ':cry: :~(', 'icon_cry.gif', 'FICON_CRY', 'Y', 70, 16, 16) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (76, 'S', ':evil: >:-<', 'icon_evil.gif', 'FICON_EVIL', 'N', 80, 16, 16) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (77, 'S', ';) ;-)', 'icon_wink.gif', 'FICON_WINK', 'N', 20, 16, 16) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (78, 'S', ':!:', 'icon_exclaim.gif', 'FICON_EXCLAIM', 'Y', 130, 16, 16) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (79, 'S', ':?:', 'icon_question.gif', 'FICON_QUESTION', 'Y', 120, 16, 16) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (80, 'S', ':idea:', 'icon_idea.gif', 'FICON_IDEA', 'Y', 140, 16, 16) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (81, 'S', ':| :-|', 'icon_neutral.gif', 'FICON_NEUTRAL', 'N', 60, 16, 16) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (82, 'I', '', 'icon1.gif', 'FICON_NOTE', 'Y', 150, 15, 15) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (83, 'I', '', 'icon2.gif', 'FICON_DIRRECTION', 'Y', 150, 15, 15) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (84, 'I', '', 'icon3.gif', 'FICON_IDEA2', 'Y', 150, 15, 15) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (85, 'I', '', 'icon4.gif', 'FICON_ATTANSION', 'Y', 150, 15, 15) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (86, 'I', '', 'icon5.gif', 'FICON_QUESTION2', 'Y', 150, 15, 15) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (87, 'I', '', 'icon6.gif', 'FICON_BAD', 'Y', 150, 15, 15) ;
insert  into b_forum_smile ( ID,`TYPE`,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) values (88, 'I', '', 'icon7.gif', 'FICON_GOOD', 'Y', 150, 15, 15) ;