<?
$arTooltips = array(
	"FID" => GetMessage("FID_TIP"),
	"SORT_BY" => GetMessage("SORT_BY_TIP"),
	"SORT_ORDER" => GetMessage("SORT_ORDER_TIP"),
	"URL_TEMPLATES_INDEX" => GetMessage("URL_TEMPLATES_INDEX_TIP"),
	"URL_TEMPLATES_LIST" => GetMessage("URL_TEMPLATES_LIST_TIP"),
	"URL_TEMPLATES_READ" => GetMessage("URL_TEMPLATES_READ_TIP"),
	"URL_TEMPLATES_PROFILE_VIEW" => GetMessage("URL_TEMPLATES_PROFILE_VIEW_TIP"),
	"TOPICS_PER_PAGE" => GetMessage("TOPICS_PER_PAGE_TIP"),
	"DATE_TIME_FORMAT" => GetMessage("DATE_TIME_FORMAT_TIP"),
	"SHOW_FORUM_ANOTHER_SITE" => GetMessage("SHOW_FORUM_ANOTHER_SITE_TIP"),
	"SET_NAVIGATION" => GetMessage("SET_NAVIGATION_TIP"),
	"DISPLAY_PANEL" => GetMessage("DISPLAY_PANEL_TIP"),
	"CACHE_TYPE" => GetMessage("CACHE_TYPE_TIP"),
	"CACHE_TIME" => GetMessage("CACHE_TIME_TIP"),
	"SET_TITLE" => GetMessage("SET_TITLE_TIP"),
	"PAGER_DESC_NUMBERING" => GetMessage("PAGER_DESC_NUMBERING_TIP"),
	"PAGER_SHOW_ALWAYS" => GetMessage("PAGER_SHOW_ALWAYS_TIP"),
	"PAGER_TITLE" => GetMessage("PAGER_TITLE_TIP"),
	"PAGER_TEMPLATE" => GetMessage("PAGER_TEMPLATE_TIP"),
);
?>