CREATE TABLE b_search_content
(
	ID			INT(11)		NOT NULL auto_increment,
	DATE_CHANGE		DATETIME	NOT NULL,
	MODULE_ID		VARCHAR(50)	NOT NULL,
	ITEM_ID			VARCHAR(255)	NOT NULL,
	LID			CHAR(2)		NOT NULL,
	CUSTOM_RANK		INT(11)		NOT NULL DEFAULT 0,
	URL			TEXT		NULL,
	TITLE			TEXT		NULL,
	BODY			TEXT		NULL,
	TAGS			TEXT		NULL,
	SEARCHABLE_CONTENT	LONGTEXT	NULL,
	PARAM1			TEXT		NULL,
	PARAM2			TEXT		NULL,
	UPD 			varchar(32)	NULL,
	DATE_FROM 		DATETIME	NULL,
	DATE_TO 		DATETIME	NULL,
	PRIMARY KEY(ID),
	UNIQUE  UX_B_SEARCH_CONTENT(MODULE_ID, ITEM_ID)
);
CREATE INDEX IX_B_SEARCH_CONTENT_1 ON b_search_content(MODULE_ID, PARAM1(50), PARAM2(50));

CREATE TABLE b_search_content_param
(
	SEARCH_CONTENT_ID INT(11) NOT NULL,
	PARAM_NAME VARCHAR(100) NOT NULL,
	PARAM_VALUE VARCHAR(100) NOT NULL,
	KEY IX_B_SEARCH_CONTENT_PARAM (SEARCH_CONTENT_ID, PARAM_NAME)
);

CREATE TABLE b_search_content_right
(
	SEARCH_CONTENT_ID INT(11) NOT NULL,
	GROUP_CODE VARCHAR(100) NOT NULL,
	UNIQUE UX_B_SEARCH_CONTENT_RIGHT (SEARCH_CONTENT_ID, GROUP_CODE)
);

CREATE TABLE b_search_user_right
(
	USER_ID INT(11) NOT NULL,
	GROUP_CODE VARCHAR(100) NOT NULL,
	UNIQUE UX_B_SEARCH_USER_RIGHT (USER_ID, GROUP_CODE)
);

CREATE TABLE b_search_content_site
(
	SEARCH_CONTENT_ID	INT(18)		NOT NULL,
	SITE_ID			CHAR(2)		NOT NULL,
	URL			TEXT,
	PRIMARY KEY PK_B_IBLOCK_SITE(SEARCH_CONTENT_ID, SITE_ID)
);

CREATE TABLE b_search_content_stem
(
	SEARCH_CONTENT_ID	INT(11)		NOT NULL,
	LANGUAGE_ID		CHAR(2)		NOT NULL,
	STEM			VARCHAR(50) binary NOT NULL,
	TF			FLOAT		NOT NULL,
	UNIQUE KEY UX_B_SEARCH_CONTENT_STEM (STEM, LANGUAGE_ID, TF, SEARCH_CONTENT_ID),
	KEY IND_B_SEARCH_CONTENT_STEM (SEARCH_CONTENT_ID)
)
DELAY_KEY_WRITE=1;

CREATE TABLE b_search_content_title
(
	SEARCH_CONTENT_ID	INT(11)		NOT NULL,
	SITE_ID			CHAR(2)		NOT NULL,
	WORD			VARCHAR(100)	NOT NULL,
	POS			INT(11)		NOT NULL,
	UNIQUE KEY UX_B_SEARCH_CONTENT_TITLE (SITE_ID, WORD, SEARCH_CONTENT_ID, POS),
	KEY IND_B_SEARCH_CONTENT_TITLE (SEARCH_CONTENT_ID)
)
DELAY_KEY_WRITE=1;

CREATE TABLE b_search_content_freq
(
	STEM			VARCHAR(50) binary NOT NULL default '',
	LANGUAGE_ID		CHAR(2)		NOT NULL,
	SITE_ID			CHAR(2),
	FREQ			FLOAT		NOT NULL,
	TF			FLOAT,
	UNIQUE KEY UX_B_SEARCH_CONTENT_FREQ (STEM, LANGUAGE_ID, SITE_ID)
);

CREATE TABLE b_search_custom_rank
(
	ID			INT(11)		NOT NULL auto_increment,
	SITE_ID			CHAR(2)		NOT NULL,
	MODULE_ID		VARCHAR(200)	NOT NULL,
	PARAM1			TEXT		NULL,
	PARAM2			TEXT		NULL,
	ITEM_ID			VARCHAR(255)	NULL,
	RANK			INT(11)		NOT NULL DEFAULT 0,
	APPLIED			CHAR(1)		NOT NULL DEFAULT 'N',
	PRIMARY KEY (ID),
	KEY IND_B_SEARCH_CUSTOM_RANK (SITE_ID,MODULE_ID)
);

CREATE TABLE b_search_tags
(
	SEARCH_CONTENT_ID INT(11) NOT NULL,
	SITE_ID CHAR(2) NOT NULL,
	NAME VARCHAR(255) binary NOT NULL,
	PRIMARY KEY PK_B_SEARCH_TAGS (SEARCH_CONTENT_ID, SITE_ID, NAME),
	KEY IX_B_SEARCH_TAGS_0 (NAME)
)
DELAY_KEY_WRITE=1;

CREATE TABLE b_search_suggest
(
	ID			INT(11)		NOT NULL auto_increment,
	SITE_ID			CHAR(2)		NOT NULL,
	FILTER_MD5		VARCHAR(32)	NOT NULL,
	PHRASE			VARCHAR(250)	NOT NULL,
	RATE			FLOAT		NOT NULL,
	TIMESTAMP_X		DATETIME	NOT NULL,
	RESULT_COUNT		INT(11)		NOT NULL,
	PRIMARY KEY PK_B_SEARCH_SUGGEST (ID),
	KEY IND_B_SEARCH_SUGGEST (FILTER_MD5, PHRASE(50), RATE),
	KEY IND_B_SEARCH_SUGGEST_PHRASE (PHRASE(50), RATE),
	KEY IND_B_SEARCH_SUGGEST_TIME (TIMESTAMP_X)
);
