<?
$arTooltips = array(
	"PATH_TO_BASKET" => GetMessage("PATH_TO_BASKET_TIP"),
	"PATH_TO_PERSONAL" => GetMessage("PATH_TO_PERSONAL_TIP"),
	"PATH_TO_AUTH" => GetMessage("PATH_TO_AUTH_TIP"),
	"PATH_TO_PAYMENT" => GetMessage("PATH_TO_PAYMENT_TIP"),
	"ALLOW_PAY_FROM_ACCOUNT" => GetMessage("ALLOW_PAY_FROM_ACCOUNT_TIP"),
	"SHOW_MENU" => GetMessage("SHOW_MENU_TIP"),
	"SET_TITLE" => GetMessage("SET_TITLE_TIP"),
	"USE_AJAX_LOCATIONS" => GetMessage("USE_AJAX_LOCATIONS_TIP"),
	"SHOW_AJAX_DELIVERY_LINK" => GetMessage("SHOW_AJAX_DELIVERY_LINK_TIP"),
	"COUNT_DELIVERY_TAX" => GetMessage("COUNT_DELIVERY_TAX_TIP"),
	"COUNT_DISCOUNT_4_ALL_QUANTITY" => GetMessage("COUNT_DISCOUNT_4_ALL_QUANTITY_TIP"),
        "PRICE_VAT_INCLUDE" => GetMessage("PRICE_VAT_INCLUDE_TIP"),
	"PRICE_VAT_SHOW_VALUE" => GetMessage("PRICE_VAT_SHOW_VALUE_TIP"),
);
?>