<?
$arTooltips = array(
	"COURSE_ID" => GetMessage("COURSE_ID_TIP"),
	"COURSE_DETAIL_TEMPLATE" => GetMessage("COURSE_DETAIL_TEMPLATE_TIP"),
	"CHAPTER_DETAIL_TEMPLATE" => GetMessage("CHAPTER_DETAIL_TEMPLATE_TIP"),
	"LESSON_DETAIL_TEMPLATE" => GetMessage("LESSON_DETAIL_TEMPLATE_TIP"),
	"SELF_TEST_TEMPLATE" => GetMessage("SELF_TEST_TEMPLATE_TIP"),
	"TESTS_LIST_TEMPLATE" => GetMessage("TESTS_LIST_TEMPLATE_TIP"),
	"TEST_DETAIL_TEMPLATE" => GetMessage("TEST_DETAIL_TEMPLATE_TIP"),
	"CHECK_PERMISSIONS" => GetMessage("CHECK_PERMISSIONS_TIP"),
	"SET_TITLE" => GetMessage("SET_TITLE_TIP"),
);
?>