<?
$arTooltips = array(
	"SITE_LIST" => GetMessage("SITE_LIST_TIP"),
	"GROUP_PERMISSIONS" => GetMessage("GROUP_PERMISSIONS_TIP"),
	"USE_ZIP" => GetMessage("USE_ZIP_TIP"),
	"EXPORT_PAYED_ORDERS" => GetMessage("EXPORT_PAYED_ORDERS_TIP"),
	"EXPORT_ALLOW_DELIVERY_ORDERS" => GetMessage("EXPORT_ALLOW_DELIVERY_ORDERS_TIP"),
	"EXPORT_FINAL_ORDERS" => GetMessage("EXPORT_FINAL_ORDERS_TIP"),
	"FINAL_STATUS_ON_DELIVERY" => GetMessage("FINAL_STATUS_ON_DELIVERY_TIP"),
	"REPLACE_CURRENCY" => GetMessage("REPLACE_CURRENCY_TIP"),
);
?>