<?
$arTooltips = array(
	"FID" => GetMessage("FID_TIP"),
	"TID" => GetMessage("TID_TIP"),
	"MID" => GetMessage("MID_TIP"),
	"URL_TEMPLATES_INDEX" => GetMessage("URL_TEMPLATES_INDEX_TIP"),
	"URL_TEMPLATES_LIST" => GetMessage("URL_TEMPLATES_LIST_TIP"),
	"URL_TEMPLATES_READ" => GetMessage("URL_TEMPLATES_READ_TIP"),
	"URL_TEMPLATES_PROFILE_VIEW" => GetMessage("URL_TEMPLATES_PROFILE_VIEW_TIP"),
	"URL_TEMPLATES_TOPIC_SEARCH" => GetMessage("URL_TEMPLATES_TOPIC_SEARCH_TIP"),
	"PATH_TO_SMILE" => GetMessage("PATH_TO_SMILE_TIP"),
	"PATH_TO_ICON" => GetMessage("PATH_TO_ICON_TIP"),
	"WORD_LENGTH" => GetMessage("WORD_LENGTH_TIP"),
	"IMAGE_SIZE" => GetMessage("IMAGE_SIZE_TIP"),
	"DATE_FORMAT" => GetMessage("DATE_FORMAT_TIP"),
	"DATE_TIME_FORMAT" => GetMessage("DATE_TIME_FORMAT_TIP"),
	"SET_NAVIGATION" => GetMessage("SET_NAVIGATION_TIP"),
	"SET_TITLE" => GetMessage("SET_TITLE_TIP"),
	"CACHE_TYPE" => GetMessage("CACHE_TYPE_TIP"),
	"CACHE_TIME" => GetMessage("CACHE_TIME_TIP"),
);
?>