<?
$arTooltips = array(
	"MESSAGE_COUNT" => GetMessage("MESSAGE_COUNT_TIP"),
	"PATH_TO_BLOG" => GetMessage("PATH_TO_BLOG_TIP"),
	"PATH_TO_BLOG_CATEGORY" => GetMessage("PATH_TO_BLOG_CATEGORY_TIP"),
	"PATH_TO_POST" => GetMessage("PATH_TO_POST_TIP"),
	"PATH_TO_POST_EDIT" => GetMessage("PATH_TO_POST_EDIT_TIP"),
	"PATH_TO_USER" => GetMessage("PATH_TO_USER_TIP"),
	"PATH_TO_SMILE" => GetMessage("PATH_TO_SMILE_TIP"),
	"BLOG_VAR" => GetMessage("BLOG_VAR_TIP"),
	"POST_VAR" => GetMessage("POST_VAR_TIP"),
	"USER_VAR" => GetMessage("USER_VAR_TIP"),
	"PAGE_VAR" => GetMessage("PAGE_VAR_TIP"),
	"BLOG_URL" => GetMessage("BLOG_URL_TIP"),
	"YEAR" => GetMessage("YEAR_TIP"),
	"MONTH" => GetMessage("MONTH_TIP"),
	"DAY" => GetMessage("DAY_TIP"),
	"CATEGORY_ID" => GetMessage("CATEGORY_ID_TIP"),
	"CACHE_TYPE" => GetMessage("CACHE_TYPE_TIP"),
	"CACHE_TIME" => GetMessage("CACHE_TIME_TIP"),
	"CACHE_TIME_LONG" => GetMessage("CACHE_TIME_LONG_TIP"),
	"SET_NAV_CHAIN" => GetMessage("SET_NAV_CHAIN_TIP"),
	"SET_TITLE" => GetMessage("SET_TITLE_TIP"),
	"POST_PROPERTY_LIST" => GetMessage("POST_PROPERTY_LIST_TIP"),
);
?>