<?
global $MESS;

$MESS["SASP_PROMT"]="Вы хотите оплатить через систему <b>www.assist.ru</b>.";
$MESS["SASP_ACCOUNT_NO"]="Cчет №";
$MESS["SASP_ORDER_FROM"]=" от ";
$MESS["SASP_ORDER_SUM"]="Сумма к оплате по счету:";
$MESS["SASP_ACTION"]="Оплатить";
$MESS["SASP_NOTES_TITLE"]="Обработка заказа";
$MESS["SASP_NOTES"]="Магазин оставляет за собой право дополнительно произвести <i>телефонную авторизацию</i> платежа. Все заказы обрабатываются не в автоматическом режиме: по рабочим дням с 10:00 до 18:00 (московское время).<br><br>В связи с усилением борьбы с мошенничеством международными платежными системами транзакции по картам Visa и Eurocard/Mastercard без заполнения поля, предназначенного для указания CVV2/CVC2 (CVV2 или CVC2 - уникальное контрольное число, нанесенное на обратной стороне карты после ее номера), данными платежными системами приниматься к обработке не будут.<br><br>В системе <a href=\"http://www.assist.ru/\">Ассист</a> безопасность платежей обеспечивается использованием SSL протокола для передачи конфиденциальной информации от клиента на сервер <a href=\"http://www.assist.ru/\">системы Ассист</a> для дальнейшей обработки.<br><br>Дальнейшая передача информации осуществляется по закрытым банковским сетям, взлом которых практически невозможен.<br><br>Обработка полученных конфиденциальных данных клиента  производится в процессинговом центре <a href=\"http://www.alfabank.ru/\">КБ \"Альфа-Банк\"</a>. Таким образом, никто, даже продавец не может получить персональные и банковские данные клиента.<br><br>";
$MESS["SASP_NOTES_TITLE1"]="Безопасность передаваемой информации";
$MESS["SASP_NOTES1"]="Для защиты информации от несанкционированного доступа на этапе передачи от клиента на сервер системы используется протокол SSL 3.0, сертификат сервера (128 bit) выдан компанией <a href=\"https://www.thawte.com\">Thawte</a> - признанным центром выдачи цифровых сертификатов.<br><br>Вы можете <a href=\"https://www.thawte.com/cgi/server/certdetails.exe?code=RUASSI2\">проверить подлинность сертификата</a> сервера Ассист.";
$MESS["SASP_AS000"]="АВТОРИЗАЦИЯ УСПЕШНО ЗАВЕРШЕНА";
$MESS["SASP_AS001"]="АВТОРИЗАЦИЯ УСПЕШНО ЗАВЕРШЕНА (С CVC2)";
$MESS["SASP_AS010"]="ПРЕДАВТОРИЗАЦИЯ УСПЕШНО ЗАВЕРШЕНА";
$MESS["SASP_AS011"]="ПРЕДАВТОРИЗАЦИЯ УСПЕШНО ЗАВЕРШЕНА (С CVC2)";
$MESS["SASP_AS020"]="ПОСТАВТОРИЗАЦИЯ УСПЕШНО ЗАВЕРШЕНА";
$MESS["SASP_AS100"]="ОТКАЗ В АВТОРИЗАЦИИ";
$MESS["SASP_AS101"]="ОТКАЗ В АВТОРИЗАЦИИ. Ошибочный номер платежного средства";
$MESS["SASP_AS102"]="ОТКАЗ В АВТОРИЗАЦИИ. Недостаточно средств";
$MESS["SASP_AS104"]="ОТКАЗ В АВТОРИЗАЦИИ. Неверный срок действия карты";
$MESS["SASP_AS105"]="ОТКАЗ В АВТОРИЗАЦИИ. Превышен лимит";
$MESS["SASP_AS106"]="ОТКАЗ В АВТОРИЗАЦИИ. Неверный PIN";
$MESS["SASP_AS107"]="ОТКАЗ В АВТОРИЗАЦИИ. Ошибка приема данных";
$MESS["SASP_AS108"]="ОТКАЗ В АВТОРИЗАЦИИ. Подозрение на мошенничество";
$MESS["SASP_AS109"]="ОТКАЗ В АВТОРИЗАЦИИ. Превышен лимит операций Assist";
$MESS["SASP_AS200"]="ПОВТОРИТЕ АВТОРИЗАЦИЮ";
$MESS["SASP_AS300"]="АВТОРИЗАЦИЯ В ПРОЦЕССЕ. ЖДИТЕ";
$MESS["SASP_AS400"]="ПЛАТЕЖА С ТАКИМИ ПАРАМЕТРАМИ НЕ СУЩЕСТВУЕТ";
$MESS["SASP_AS998"]="ОШИБКА СИСТЕМЫ. Свяжитесь с ASSIST";
$MESS["SALE_ASSIST_DESCRIPTION"]="<a href=\"http://www.assist.ru\" target=\"_blank\">http://www.assist.ru</a>";
$MESS["SALE_ASSIST_SHOP_IDP_NAME"]="Код магазина";
$MESS["SALE_ASSIST_SHOP_IDP_DESCR"]="Код магазина, который получен от Assist.ru";
$MESS["SALE_ASSIST_SHOP_LOGIN_NAME"]="Логин";
$MESS["SALE_ASSIST_SHOP_LOGIN_DESCR"]="Логин, который получен от Assist.ru";
$MESS["SALE_ASSIST_SHOP_PASSWORD_NAME"]="Пароль";
$MESS["SALE_ASSIST_SHOP_PASSWORD_DESCR"]="Пароль, который получен от Assist.ru";
$MESS["SALE_ASSIST_FIRST_NAME_NAME"]="Имя покупателя";
$MESS["SALE_ASSIST_LAST_NAME_NAME"]="Фамилия покупателя";
$MESS["SALE_ASSIST_DEMO_NAME"]="Работа в тестовом режиме";
$MESS["SALE_ASSIST_EMAIL_NAME"] = "E-mail покупателя";
$MESS["SALE_ASSIST_PHONE_NAME"] = "Телефон покупателя";
$MESS["SALE_ASSIST_ADDRESS_NAME"] = "Адрес покупателя";
$MESS["SALE_ASSIST_MIDDLE_NAME_NAME"] = "Отчество покупателя";
$MESS["SALE_ASSIST_PAYMENT_NAME"] = "Способ оплаты";
$MESS["SALE_ASSIST_PAYMENT_CardPayment_NAME"] = "Использовать авторизационные страницы ASSIST для авторизации";
$MESS["SALE_ASSIST_PAYMENT_WalletPayment_NAME"] = "Использовать SET-авторизацию";
$MESS["SALE_ASSIST_PAYMENT_WebMoneyPayment_NAME"] = "Использовать платежную систему WebMoney Transfer";
$MESS["SALE_ASSIST_PAYMENT_EPortPayment_NAME"] = "Использовать платежную систему E-Port";
$MESS["SALE_ASSIST_PAYMENT_KreditPilotPayment_NAME"] = "Использовать платежную систему KreditPilot";
$MESS["SALE_ASSIST_PAYMENT_PayCashPayment_NAME"] = "Использовать платежную систему PayCash";
$MESS["SALE_ASSIST_PAYMENT_CardPayment_DESC"] = "1 - использовать, 0 - не использовать";
$MESS["SALE_ASSIST_PAYMENT_WalletPayment_DESC"] = "1 - использовать, 0 - не использовать";
$MESS["SALE_ASSIST_PAYMENT_EPortPayment_DESC"] = "1 - использовать, 0 - не использовать";
$MESS["SALE_ASSIST_PAYMENT_KreditPilotPayment_DESC"] = "1 - использовать, 0 - не использовать";
$MESS["SALE_ASSIST_PAYMENT_PayCashPayment_DESC"] = "1 - использовать, 0 - не использовать";
$MESS["SALE_ASSIST_PAYMENT_WebMoneyPayment_DESC"] = "1 - использовать, 0 - не использовать";

$MESS["SALE_ASSIST_PAYMENT_RapidaPayment_NAME"] = "Использовать платежную систему Rapida";
$MESS["SALE_ASSIST_PAYMENT_RapidaPayment_DESC"] = "1 - использовать, 0 - не использовать";
$MESS["SALE_ASSIST_PAYMENT_AssistIDCCPayment_NAME"] = "Использовать оплату кредитной картой с использованием Assist®ID";
$MESS["SALE_ASSIST_PAYMENT_AssistIDCCPayment_DESC"] = "1 - использовать, 0 - не использовать";
$MESS["SALE_ASSIST_PAYMENT_EPBeelinePayment_NAME"] = "Использовать мобильный кошелек Билайн";
$MESS["SALE_ASSIST_PAYMENT_EPBeelinePayment_DESC"] = "1 - использовать, 0 - не использовать";

$MESS["SALE_ASSIST_DEMO_DESC"] = "Когда магазин находится в тестовом режиме, авторизации в Платежный Центр не поступают, а сервер ASSIST ожидает от магазина  передачи обязательного параметра DemoResult, в котором содержится желаемый результат платежа (Response_Code), который и генерируется в ответе покупателю.";

$MESS["SALE_ASSIST_SHOULD_PAY"] = "Сумма к оплате";
$MESS["SALE_ASSIST_DESC_SHOULD_PAY"] = "";
$MESS["SALE_ASSIST_CURRENCY"] = "Валюта оплаты";
$MESS["SALE_ASSIST_DESC_CURRENCY"] = "";
$MESS["SALE_ASSIST_ORDER_ID"] = "Номер заказа";
$MESS["SALE_ASSIST_DESC_ORDER_ID"] = "Номер заказа в вашем Интернет-магазине";
$MESS["SALE_ASSIST_SUCCESS_URL"] = "Адрес при успешной оплате";
$MESS["SALE_ASSIST_DESC_SUCCESS_URL"] = "URL скрипта (на веб-сайте продавца) обрабатывающего оповещения о результате платежа";
$MESS["SALE_ASSIST_FAIL_URL"] = "Адрес при ошибке оплаты";
$MESS["SALE_ASSIST_DESC_FAIL_URL"] = "URL (на веб-сайте продавца) для перенаправления плательщика при неуспешном платеже";
$MESS["SALE_ASSIST_DATE_INSERT"] = "Дата создания заказа";
$MESS["SALE_ASSIST_DESC_DATE_INSERT"] = "";
?>