<?
$arTooltips = array(
	"COURSE_ID" => GetMessage("COURSE_ID_TIP"),
	"CHAPTER_ID" => GetMessage("CHAPTER_ID_TIP"),
	"CHAPTER_DETAIL_TEMPLATE" => GetMessage("CHAPTER_DETAIL_TEMPLATE_TIP"),
	"LESSON_DETAIL_TEMPLATE" => GetMessage("LESSON_DETAIL_TEMPLATE_TIP"),
	"CHECK_PERMISSIONS" => GetMessage("CHECK_PERMISSIONS_TIP"),
	"SET_TITLE" => GetMessage("SET_TITLE_TIP"),
	"CACHE_TYPE" => GetMessage("CACHE_TYPE_TIP"),
	"CACHE_TIME" => GetMessage("CACHE_TIME_TIP"),
);
?>