<?
$arTooltips = array(
	"IBLOCK_TYPE" => GetMessage("IBLOCK_TYPE_TIP"),
	"IBLOCK_ID" => GetMessage("IBLOCK_ID_TIP"),
	"SECTION_SORT_FIELD" => GetMessage("SECTION_SORT_FIELD_TIP"),
	"SECTION_SORT_ORDER" => GetMessage("SECTION_SORT_ORDER_TIP"),
	"ELEMENT_SORT_FIELD" => GetMessage("ELEMENT_SORT_FIELD_TIP"),
	"ELEMENT_SORT_ORDER" => GetMessage("ELEMENT_SORT_ORDER_TIP"),
	"FILTER_NAME" => GetMessage("FILTER_NAME_TIP"),
	"FIELD_CODE" => GetMessage("FIELD_CODE_TIP"),
	"PROPERTY_CODE" => GetMessage("PROPERTY_CODE_TIP"),
	"SECTION_URL" => GetMessage("SECTION_URL_TIP"),
	"DETAIL_URL" => GetMessage("DETAIL_URL_TIP"),
	"DISPLAY_PANEL" => GetMessage("DISPLAY_PANEL_TIP"),
	"CACHE_TYPE" => GetMessage("CACHE_TYPE_TIP"),
	"CACHE_TIME" => GetMessage("CACHE_TIME_TIP"),
	"CACHE_FILTER" => GetMessage("CACHE_FILTER_TIP"),
	"SECTION_COUNT" => GetMessage("SECTION_COUNT_TIP"),
	"ELEMENT_COUNT" => GetMessage("ELEMENT_COUNT_TIP"),
	"LINE_ELEMENT_COUNT" => GetMessage("LINE_ELEMENT_COUNT_TIP"),
);
?>