<?
$arTooltips = array(
	"IBLOCK_TYPE" => GetMessage("IBLOCK_TYPE_TIP"),
	"IBLOCK_ID" => GetMessage("IBLOCK_ID_TIP"),
	"SECTION_ID" => GetMessage("SECTION_ID_TIP"),
	"SECTION_CODE" => GetMessage("SECTION_CODE_TIP"),
	"INDEX_URL" => GetMessage("INDEX_URL_TIP"),
	"SECTION_URL" => GetMessage("SECTION_URL_TIP"),
	"DISPLAY_PANEL" => GetMessage("DISPLAY_PANEL_TIP"),
	"SET_TITLE" => GetMessage("SET_TITLE_TIP"),
	"UPLOAD_MAX_FILE" => GetMessage("UPLOAD_MAX_FILE_TIP"),
	"UPLOAD_MAX_FILE_SIZE" => GetMessage("UPLOAD_MAX_FILE_SIZE_TIP"),
	"ALBUM_PHOTO_THUMBS_WIDTH" => GetMessage("ALBUM_PHOTO_THUMBS_WIDTH_TIP"),
	"ALBUM_PHOTO_WIDTH" => GetMessage("ALBUM_PHOTO_WIDTH_TIP"),
	"THUMBS_SIZE" => GetMessage("THUMBS_SIZE_TIP"),
	"JPEG_QUALITY1" => GetMessage("JPEG_QUALITY1_TIP"),
	"PREVIEW_SIZE" => GetMessage("PREVIEW_SIZE_TIP"),
	"JPEG_QUALITY2" => GetMessage("JPEG_QUALITY2_TIP"),
	"JPEG_QUALITY" => GetMessage("JPEG_QUALITY_TIP"),
	"ADDITIONAL_SIGHTS" => GetMessage("ADDITIONAL_SIGHTS_TIP"),
	"WATERMARK_MIN_PICTURE_SIZE" => GetMessage("WATERMARK_MIN_PICTURE_SIZE_TIP"),
);
?>